### ISSUE TITLE
Ver1.0.0 TODO List

### ISSUE THREAD

**Issue by 0999312** [0999312/Sakura_mod#11]
- [x] Add Pepper, Vanilla, Grape, Rapeseed Crop.
- [x] Complete Maple Cauldron and Maple Syrup
- [ ] Add More Foods and Recipe
- [ ] Add More decorations
- [ ] Add Kakeziku like WA.
- [x] Sakura Diamond Ore and Tools.
- [x] Katana Item
- [x] SlashBlade compat, as WA/Bamboo.
// Add custom Bento.
- [x] Get raw noodle like Mapletree.
- [x] New Villager.
- [x] Taiko/Goto
- [x] Tatara
- [ ] Onsen
